CC = gcc
TARGET = kvstore
SRCS = kvstore.c reactor.c proactor.c ntyco.c kvs_array.c kvs_rbtree.c kvs_hash.c
INC = -I NtyCo/core/
LIBS = -L ./NtyCo/ -lntyco -luring


all:
	$(CC) -o $(TARGET) $(SRCS) $(INC) $(LIBS)

clean:
	rm -f $(TARGET)